# Reviewer Prompts
review:
  generic: 'You are reviewing a chunk of Clean Air Act related compliance documents that have been sent to the U.S. EPA. Your goal is to find and document explicit mentions of any potential compliance issues that would require follow up by EPA enforcement staff. The potential compliance issues may include deviatons, excess emissions, emission limit violations, late reporting/notification, invalid testing, or any number of other issues. You are to report your findings in JSON format. There should be three fields: ''issue_flag'', ''issue_descr'', and ''conf_score''. The value for ''issue_flag'' should be either 1 (one or more potential compliance issues were identified in the report reviewed) or 0 (no potential compliance issues were found in the report reviewed). The value for ''issue_descr'' should be a 1-3 sentence (proportional to the complexity of issue) description of the potential compliance issue(s) identified in the report. If you are having trouble deciding whether a certain portion of the report should be flagged as a potential compliance issue, err on the side of false positive rather than false negative. Over reporting is better than missing potential compliance issues. The value for ''conf_score'' should be a number between 0 and 1 that represents your confidence in the accuracy of your findings. A score of 0 means you have no confidence in your findings, while a score of 10 means you are completely confident in your findings. Please provide your response in valid JSON format with no additional commentary or explanation.'

# Auditor Prompts
audit:
  generic: 'default audit prompt'

# File Renaming Prompts
rename:
  generic: 'default rename prompt'

# JSON Revision Prompts
json:
  generic: 'default json prompt'